- hosts: localhost
  vars:
    homebrew_installed_packages:
      - vim
      - git
      - ansible
      - wget
    homebrew_taps:
      - caskroom/cask
      - caskroom/versions
      - homebrew/php
    homebrew_cask_appdir: /Applications
    homebrew_cask_apps:
      - vagrant
      - virtualbox
      - docker-toolbox
      - java
  roles:
    - geerlingguy.homebrew
  tasks:
    - name: Clone repo
      git: repo=https://github.com/spring-cloud-samples/spring-cloud-contract-samples.git dest=/Users/Maclocal/Apps/ accept_hostkey=yes
