- hosts: localhost
  vars:
    homebrew_installed_packages:
      - vim
      - git
      - ansible
      - wget
      - gradle
    homebrew_taps:
      - caskroom/cask
      - caskroom/versions
      - homebrew/php
    homebrew_cask_appdir: /Applications
    homebrew_cask_apps:
      - vagrant
      - virtualbox
      - docker-toolbox
      - java
  roles:
    - geerlingguy.homebrew
  tasks:
    - name: Clone elis repo
      git: repo= dest=/Users/{{ansible_user_id}}/ansible/ accept_hostkey=yes
